# Generated by Django 6.0.6 on 2026-06-26 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, default='fas fa-certificate', max_length=80)),
                ('credential', models.CharField(blank=True, max_length=120)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, default='fas fa-laptop-code', max_length=80)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='bio',
            name='about_paragraph_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='about_paragraph_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='availability_text',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='bio',
            name='career_objective',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='bio',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='hero_tagline',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='bio',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='bio',
            name='professional_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='bio',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='bio',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='bio',
            name='short_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='strengths',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='typing_text',
            field=models.TextField(blank=True, help_text='Enter one typing animation phrase per line.'),
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='bio.service')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
