# Generated by Django 6.0.6 on 2026-06-26 07:41

from django.db import migrations


def seed_dynamic_content(apps, schema_editor):
    Bio = apps.get_model('bio', 'Bio')
    Achievement = apps.get_model('bio', 'Achievement')
    Service = apps.get_model('bio', 'Service')
    ServiceFeature = apps.get_model('bio', 'ServiceFeature')
    Skill = apps.get_model('skills', 'Skill')

    bio = Bio.objects.first()
    if bio:
        defaults = {
            'professional_title': bio.title,
            'typing_text': '\n'.join([
                'MERN Stack Developer',
                'React.js Engineer',
                'Full-Stack Developer',
                'CS Student @ UMT',
                'Frontend Developer',
            ]),
            'hero_tagline': 'CS student at UMT &amp; MERN developer turning ideas into<br><strong>production-ready web experiences</strong>.',
            'resume': 'resumes/abdullah_salman_resume.pdf',
            'profile_image': 'profile/profile.jpeg',
            'availability_text': 'Open to opportunities',
            'about_paragraph_1': (
                "I'm a <strong>Computer Science student at UMT Lahore</strong> with a passion for "
                "building full-stack web applications that solve real problems. My core stack is "
                "<strong>MERN (MongoDB, Express.js, React.js, Node.js)</strong>, and I'm always "
                "expanding into adjacent technologies like Next.js, FastAPI, and machine learning."
            ),
            'about_paragraph_2': (
                "Outside of coursework, I lead web development initiatives for the "
                "<strong>Inter AI Club at UMT</strong>, build freelance projects for real clients, "
                "and compete in university coding competitions. I care deeply about clean architecture, "
                "thoughtful UI, and code that actually ships."
            ),
            'career_objective': (
                'Land a full-stack or frontend developer role where I can ship meaningful products '
                'and grow alongside a strong engineering team.'
            ),
            'strengths': 'Quick learner &middot; Strong problem-solver &middot; Team collaborator &middot; Pragmatic about shipping',
            'short_description': 'Building modern web experiences with clean code and genuine care for the user.',
            'email': 'abdullahsalman029@gmail.com',
            'phone': '+92 321 845 7902',
            'linkedin': 'https://www.linkedin.com/in/abdullah-salman-846214377',
            'github': 'https://github.com/Abdelliito',
            'location': 'Lahore, Pakistan',
        }
        for field, value in defaults.items():
            if not getattr(bio, field):
                setattr(bio, field, value)
        bio.save()

    skill_defaults = {
        'html': ('Frontend', 'fab fa-html5', 1),
        'css': ('Frontend', 'fab fa-css3-alt', 2),
        'javascript': ('Frontend', 'fab fa-js', 3),
        'react': ('Frontend', 'fab fa-react', 4),
        'node.js': ('Backend', 'fab fa-node-js', 1),
        'express.js': ('Backend', 'fas fa-server', 2),
        'fastapi': ('Backend', 'fab fa-python', 3),
        'jwt': ('Backend', 'fas fa-key', 4),
        'mongodb': ('Database', 'fas fa-database', 1),
        'mysql': ('Database', 'fas fa-database', 2),
        'database design': ('Database', 'fas fa-database', 3),
        'python': ('Tools', 'fab fa-python', 1),
        'c++': ('Tools', 'fas fa-code', 2),
        'git': ('Tools', 'fab fa-git-alt', 3),
        'github': ('Tools', 'fab fa-github', 4),
        'vs code': ('Tools', 'fas fa-code', 5),
        'vite': ('Tools', 'fas fa-bolt', 6),
        'cloudinary': ('Tools', 'fas fa-image', 7),
        'vercel': ('Tools', 'fas fa-cloud', 8),
        'render': ('Tools', 'fas fa-server', 9),
        'unity': ('Tools', 'fas fa-gamepad', 10),
        'c#': ('Tools', 'fas fa-hashtag', 11),
    }
    for skill in Skill.objects.all():
        key = skill.name.strip().lower()
        for name_key, values in skill_defaults.items():
            if key == name_key or name_key in key:
                category, icon, order = values
                skill.category = category
                if not skill.icon:
                    skill.icon = icon
                if not skill.display_order:
                    skill.display_order = order
                skill.save()
                break

    achievements = [
        {
            'title': 'MERN Stack Development',
            'organization': 'Web Ascend, co-powered by IEEE UMT Branch',
            'description': 'Bootcamp credential demonstrating proficiency in MERN stack development and full-stack web application design.',
            'date': 'March 2026',
            'icon': 'fas fa-certificate',
            'credential': 'No. WA-P2-2026-001',
            'display_order': 1,
        },
        {
            'title': 'University Coding Competition',
            'organization': 'UMT, Lahore',
            'description': 'Participated in university-level coding competition, solving algorithmic challenges and competitive programming problems.',
            'date': '2024',
            'icon': 'fas fa-trophy',
            'credential': '',
            'display_order': 2,
        },
        {
            'title': 'Strong Academic Performance',
            'organization': 'UMT - CS Program',
            'description': 'Demonstrated strong academic performance in Data Structures & Algorithms, Database Systems, and Software Engineering.',
            'date': '2023 - Present',
            'icon': 'fas fa-star',
            'credential': '',
            'display_order': 3,
        },
    ]
    for item in achievements:
        Achievement.objects.get_or_create(title=item['title'], defaults=item)

    services = [
        {
            'title': 'Frontend Development',
            'description': 'Pixel-perfect, accessible UIs built with React.js and Tailwind CSS - performant, responsive, and cross-browser compatible.',
            'icon': 'fas fa-laptop-code',
            'display_order': 1,
            'features': ['React.js SPAs', 'Responsive design', 'Modern UI/UX', 'Performance optimization'],
        },
        {
            'title': 'MERN Stack Development',
            'description': 'Full-stack applications built on MongoDB, Express.js, React.js, and Node.js - from database design to deployment.',
            'icon': 'fas fa-layer-group',
            'display_order': 2,
            'features': ['Full-stack architecture', 'REST API design', 'Auth & role-based access', 'Cloud deployment'],
        },
        {
            'title': 'API Integration',
            'description': 'Third-party API integration, real-time data fetching, and optimized state management with TanStack Query & Axios.',
            'icon': 'fas fa-plug',
            'display_order': 3,
            'features': ['Third-party API integration', 'Real-time data fetching', 'TanStack Query', 'Cloudinary media'],
        },
        {
            'title': 'Responsive Web Development',
            'description': 'Mobile-first websites and landing pages that look sharp and load fast across all screen sizes and devices.',
            'icon': 'fas fa-mobile-alt',
            'display_order': 4,
            'features': ['Mobile-first approach', 'Landing pages', 'Cross-browser support', 'Vercel / Render deployment'],
        },
    ]
    for item in services:
        features = item.pop('features')
        service, _ = Service.objects.get_or_create(title=item['title'], defaults=item)
        if not ServiceFeature.objects.filter(service=service).exists():
            for feature in features:
                ServiceFeature.objects.create(service=service, text=feature)


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0002_achievement_service_bio_about_paragraph_1_and_more'),
        ('skills', '0002_alter_skill_options_skill_category_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_dynamic_content, migrations.RunPython.noop),
    ]
